all:
  vars:
    outputs: {}
    exposed_ports:
      80:
      443:
      680:
      6443:
      8080:
      9000:
      9001:
      29418:
    web_ip: 192.168.222.222
    gerrit_version: 2.15.18
    creds_admin_username: admin
    creds_admin_password: admin
    creds_admin_password_md5: ISMvKXpXpadDiUoOSoAfww==
    creds_ldap_bind_password: admin
    creds_ldap_bind_username: cn=admin,dc=example,dc=org
    swarm_base_dir: /docker
    swarm_stacks_dir: /docker/stacks
    swarm_mounts_dir: /docker/mounts
    # TODO: Setup some sort of mount
    use_efs: false
    use_nfs: true
    compose_version: 3.8
    jenkins_nodes:
      openjdk:
        image: openjdk:17-slim
        count: 1
    users:
      jjas:
        name: Kuba Jasko
        email: kubajasko@hotmail.com
      jblo:
        name: Joe Reginald Bloggs
docker:
  hosts:
    gerrit:
      ansible_connection: docker

